### ISSUE TITLE
feature: MDX support

### ISSUE THREAD

**Issue by nickali** [MeanderingProgrammer/render-markdown.nvim#120]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Similar to improving markdown files visually, it would be great if this plugin worked for mdx files as well.

### Describe alternatives you've considered

I tried the following, but it didn't work for mdx files:

```lua
return {
  {
    "MeanderingProgrammer/render-markdown.nvim",
    opts = {},
    dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.icons" }, -- if you use standalone mini plugins
    config = function()
      require("render-markdown").setup {
        file_types = { "markdown", "mdx" },
      }
    end,
  },
}
```

I've got the mdx-analyzer and marksman LSPs installed as well.

Perhaps custom handlers could work?

**Comment by MeanderingProgrammer** [comment]
Hmm, I think how I support this would depend on how users configure treesitter to work with `mdx` files. In your case how do you setup highlighting for `mdx` files?

Do you download a specific parser, I don't see one in [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter)?

Or do you configure a filetype with something like `vim.filetype.add`?

**Comment by MeanderingProgrammer** [comment]
To get this plugin to work in `mdx` files you need to get `markdown` to be recognized in the file. 

One way to do this is to add the following somewhere in your config so that mdx files are recognized and parsed as `markdown`:

```lua
vim.filetype.add({
    extension = { mdx = 'mdx' },
})
vim.treesitter.language.register('markdown', 'mdx')
```

Then configure the plugin like in your example:

```lua
require('render-markdown').setup({
    file_types = { 'markdown', 'mdx' },
})
```

However this will not look great as all the TS/JS will fail to be highlighted correctly since the entire buffer is read as markdown.

You'll need to do language injections somehow, maybe there's a plugin that does a better job of this but I could not find one. Hope this helps!

**Comment by barraIhsan** [comment]
for the people that wanted this, you can follow this article
https://phelipetls.github.io/posts/mdx-syntax-highlight-treesitter-nvim/

and there's also the plugin if you don't want to set it up manually
https://github.com/davidmh/mdx.nvim
