### ISSUE TITLE
bug: Transparency issues with callouts

### ISSUE THREAD

**Issue by realhackcraft** [MeanderingProgrammer/render-markdown.nvim#127]
### Neovim version (nvim -v)

0.10.0

### Operating system

MacOS

### Terminal emulator / GUI

WezTerm

### Describe the bug

With a transparent terminal, I noticed that callout "headers" have a transparent background, while the callouts themselves at a background color. 

### Expected behavior

The background to be transparent, or an option that allows me to turn on and off the background for block quotes and callouts.

### Healthcheck output

```
==============================================================================
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 6.0.13
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- OK latex2text: installed

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```

### Plugin configuration

```lua
return {
  "MeanderingProgrammer/render-markdown.nvim",
  opts = { code = { style = "language" } },
  dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" }, -- if you prefer nvim-web-devicons
  ft = { "markdown" },
  cmd = { "RenderMarkdown" },
}
```

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

### Additional information

This background is also present with block quotes, which leads me to believe this to be a problem with treesitter. Here are some screenshots:
![Screenshot 2024-08-10 at 22 17 20](https://github.com/user-attachments/assets/d2c16b60-25f3-4bd9-a2f8-ee33316d1d8a)
![Screenshot 2024-08-10 at 22 18 11](https://github.com/user-attachments/assets/9f5632c9-23cd-49cd-bdad-7bd8f012d0a4)

```markdown
> This is a test blockquote.

> [!WARNING] This might be dangerous!
> be careful!
```

I'm using NvChad, so I'm not sure what is the best way to isolate this plugin. What I ended up doing to see if another plugin is causing this is to keep all the builtin plugins and render-markdown, and skip all my other plugins.

With only this plugin enabled, I can still reproduce this.

Sorry in advance if this should be reported in treesitter markdown

**Comment by MeanderingProgrammer** [comment]
This is definitely not an issue with treesitter so this is the right place to figure out what's going on :)

Which color scheme do you use?

For the callout headers by default we use the various `Diagnostic` highlight groups, so for a warning we set `DiagnosticWarn`. In this case it looks like your color scheme does not set a background for diagnostics, which makes sense and is why the background is transparent.

For the quote body we actually don't set any highlight at all, only for the starting `>` character. So if you disable this plugin and write a block quote I imagine you'll see the same non-transparent background. Which is kind of strange, I would assume users with transparent backgrounds would want quotes to also have a transparent background, since multi line block quotes would look strange otherwise.

The highlight group for block quotes defined by `nvim-treesitter` is `@markup.quote.markdown`. So whatever your color scheme sets this to is what determines the behavior of the block quote body. You can either manually overwrite this in your config, or potentially the color scheme allows you to set some configuration option that makes this happen.

**Comment by realhackcraft** [comment]
I couldn't find `@markup.quote.markdown`, but `@markup.quote` exists for me and I think that's what's causing the background color. `:hi @markup.quote` returns `@markup.quote xxx guibg=#2e2e2e`.

This should be an issue with NvChad then, because that bundles nvim-treesitter and controls the themes.

I'll report this there. Thanks for you help!
