### ISSUE TITLE
feature: Callout for mkdocs-material theme

### ISSUE THREAD

**Issue by ambaradan** [MeanderingProgrammer/render-markdown.nvim#152]
### Callout for mkdocs-material theme

Hi, and first of all thanks for all the work on this plugin, it's really cool!
I wanted to ask if there is a way to modify the `callouts` to use them with *mkdocs-material* tags, I think the problem lies in the fact that the tag, for example for note, has a blank space `!!! note` and is not recognized if inserted instead of `[!NOTE]`.
If helpful, for reference:

```txt
https://squidfunk.github.io/mkdocs-material/reference/admonitions/
```

The perfect solution would be to be able to insert the `material` tag, such as:

```lua
note = { raw = '!!! note', rendered = '󰋽 Note', highlight = 'RenderMarkdownInfo' },
```

### Describe alternatives you've considered

No alternative solution, we may well continue to write documentation with the tags displayed normally:

```txt
!!! note
```

However, this functionality would make the configuration I am developing for a version of NvChad dedicated to the Markdown language more interesting.

```txt
https://github.com/ambaradan/markchad
```

**Comment by MeanderingProgrammer** [comment]
Hi, glad you are liking the plugin. Unfortunately this would not be feasible to do.

Callouts are defined as:

```
Callouts are a special instance of a 'block_quote' that start with a 'shortcut_link'
```

This is important as it means we can quickly query the buffer using treesitter to find all `shortcut_link`s.

The `!!!` syntax means nothing in markdown, at least with the current parser, and so to support this we would need to go line by line, find three exclamation marks, and since they do not rely on a block quote we would need to insert the horizontal bars to make them look nice.

It's just a little too specific and such a different implementation it would share nothing with the current callout logic.

**Comment by ambaradan** [comment]
Thank you very much for the clarification, I suspected that.
