### ISSUE TITLE
feature: option to position links icon at the start/end

### ISSUE THREAD

**Issue by mcchrish** [MeanderingProgrammer/render-markdown.nvim#156]
### Is your feature request related to a problem? Please describe.

<img width="251" alt="image" src="https://github.com/user-attachments/assets/dbb53222-e28b-448a-8aad-82eb4d047289">

In list specifically, it looks nicer if the icons are the end.

### Describe the solution you'd like

No solution.

### Describe alternatives you've considered

Just an option like:
```lua
{
  position = "end" -- default to start
}
```

**Comment by MeanderingProgrammer** [comment]
So I mocked this up in 2 different ways. 

One where I insert a space between the icon and the text when aligned to the end, and one where I don't.

Here are the results:

| Start Aligned (Current) | End Aligned no Space | End Aligned with Space |
| ---------------------- | ----------------------- | ----------------------- |
| ![left-aligned](https://github.com/user-attachments/assets/ac1ef52d-74cf-4007-9861-57951749bcd7) | ![right-aligned-no-space](https://github.com/user-attachments/assets/6183cb0c-3449-43ce-a330-b3ccffc50207) | ![right-aligned-space](https://github.com/user-attachments/assets/af6bfb09-a430-4ab2-bf33-6d540c8200f4) |

The markdown I'm testing with is:

```
- [Normal Shortcut]
- [[Basic One]] Then normal text
- [[Nickname|With Alias]] Something important
- <test@example.com> Email
- [Youtube Link](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
```

In my opinion because double width glyphs require additional space on the right, neither of the end aligned options look good, whether they are in a list or not. The spacing is a little awkward, it either ends up looking squished or like there is too much space.

Do you prefer either of the end aligned options above to the start aligned one?

**Comment by mcchrish** [comment]
> neither of the end aligned options look good

I agree. It's now a personal taste which of them looks better. I prefer with no space. In this case, it might make sense to open up a config for the padding.

**Comment by MeanderingProgrammer** [comment]
> I agree.

I'm curious, if you think neither of them look good either, why add the feature?

**Comment by echo-bravo-yahoo** [comment]
Chiming in that I'd like this feature as well, and that I'd prefer for `render-markdown` to not insert a space, but to allow users to have spaces in their icon definition (i believe this already works, but it's an elegant way to solve this issue). e.g., if i wanted more space, i might define an icon as `-   `.
