### ISSUE TITLE
feature: add an indent of the heading body relative to the heading title

### ISSUE THREAD

**Issue by russarr** [MeanderingProgrammer/render-markdown.nvim#161]
### Is your feature request related to a problem? Please describe.

If we set indent option, now indentation looks like:
```md
# heading 1
some text
    ## heading 2
    some text
```
In Obsidian i have snippet that add indentation for body after heading relative to the heading.

### Describe the solution you'd like

Is there any way, to add option to make the indentation look like this:
```md
# heading 1
    some text
    ## heading 2
        some text
```
In my opinion it looks more readable.

### Describe alternatives you've considered

Thanks for the great plugin!

**Comment by MeanderingProgrammer** [comment]
I got a working version of this as a combination of 2 features added:

- https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/cdb58fc97c49a1ab75b35d99183c35b5863e845a
- https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/a028fbe8f40b329ced721efba15a59ea31db8651

These 2 allow us to configure the starting point for which sections to indent (`skip_level`) and to skip indenting the headings of sections so that the body is offset while the heading still lines up with the content of the previous section (`skip_heading`).

Please update the plugin and give it a shot. To get the result you show use the following configuration:

```lua
require('render-markdown').setup({
    indent = {
        enabled = true,
        skip_level = 0,
        skip_heading = true,
    },
})
```

**Comment by MeanderingProgrammer** [comment]
Ah, damnit. Yeah all the block width stuff will break based on the current implementation.

Not related to those PRs, it would have been the case since I added the feature.

Will see what I can do about it.

**Comment by MeanderingProgrammer** [comment]
Should be fixed after: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/044f2d6d76712de69a79b25a7cd8311cb505a9f4

**Comment by drzhivago420** [comment]
Hey guys I'm not seeing the indentation at all, any idea what could be the issue?

this is my config:
```
return {
    'MeanderingProgrammer/render-markdown.nvim',

    ft = "markdown",

    opts = {
        indent = { enabled = on, skip_heading = true,},
    }
}
```

version:
NVIM v0.12.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377
  "render-markdown.nvim": { "branch": "main", "commit": "ff577b44bd3ab642acec0f134a7bf26b7278d137" },

![Image](https://github.com/user-attachments/assets/681fc5a5-6ce1-46a1-b9b4-3636a1566808)

**Comment by MeanderingProgrammer** [comment]
> indent = { enabled = on, skip_heading = true,},

What is `on`?

**Comment by drzhivago420** [comment]
> > indent = { enabled = on, skip_heading = true,},
> 
> What is `on`?

Damn that was a dumb mistake 😅, thank you so much
