### ISSUE TITLE
help: Quick question: Do I still need vim-markdown (or: markdown.nvim)?

### ISSUE THREAD

**Issue by sspaeti** [MeanderingProgrammer/render-markdown.nvim#167]
### Description

Hi Vlad

Thanks so much for making this. This plugin is the first that makes me Neovim more for my Notes. I'm also really enjoying the configs that I could customize. 

Quick questions I did not find an answer too, do I still need `preservim/vim-markdown`, or is that covered with your plugin or `tadmccorkle/markdown.nvim`. I'm unsure which ones are used alongside, and which ones collide. My markdown settings as of now: https://github.com/sspaeti/dotfiles/blob/08c10bc4e0eac6fce4ac12b05f33e5709dabfeac/nvim/lua/sspaeti/plugins/markdown.lua

Thanks so much, and have a great day.
Simon

**Comment by MeanderingProgrammer** [comment]
Hi, glad you're enjoying the plugin :)

I have a doc in this repo that attempts to answer this question, I haven't come across `preservim/vim-markdown` so I added it there as well though I'm unsure if my description is entirely accurate: https://github.com/MeanderingProgrammer/render-markdown.nvim/blob/main/doc/markdown-ecosystem.md.

The short answer is this plugin only does UI in neovim buffers, so any other UI plugin will clash. 

This plugin does nothing for keymaps or navigation so something like `tadmccorkle/markdown.nvim` is completely fine to use alongside this plugin.

For `preservim/vim-markdown` I think it might clash with neovim's internal `treesitter`. I'm not really sure if it's necessary in general because of that, aside from the folding related features.

**Comment by sspaeti** [comment]
Hi @MeanderingProgrammer  

Thank you so much for the kind reply and help. Your documentation is spot on, that helps me a lot. I didn't know about the obsidian.nvim conflict, atm I use both. I will check that. Also, the treesitter and vim-markdown clash is interesting, and take a look. 

Keep it going, and thanks again for the great work. It is much appreciated.

**Comment by sspaeti** [comment]
Hi @MeanderingProgrammer  

Thank you so much for the kind reply and help. Your documentation is spot on, that helps me a lot. I didn't know about the obsidian.nvim conflict, atm I use both. I will check that. Also, the treesitter and vim-markdown clash is interesting, and take a look. 

Keep it going, and thanks again for the great work. It is much appreciated.
