### ISSUE TITLE
feature: add support for visual-block and visual-line to the `render_modes` config value

### ISSUE THREAD

**Issue by hneutr** [MeanderingProgrammer/render-markdown.nvim#180]
### Is your feature request related to a problem? Please describe.

when 'v' is contained in the `render_modes` table, only the basic visual mode is rendered — when visual-line or visual-block mode is entered, rendering is turned off.

### Describe the solution you'd like

support rendering content in visual-line and visual-block mode when the `render_modes` configuration table contains 'v'.

### Describe alternatives you've considered

support rendering in `visual-line` and `visual-block` when values other than 'v' are present in the `render_modes` configuration table, eg, `vl` and `vb`.

**Comment by MeanderingProgrammer** [comment]
I'm not going to add it by default since that would assume everybody that adds `'v'` in the config wants rendering in all visual modes. Might be true for many people but there's always edge cases and there wouldn't be a way to opt out if it. 

It would be similar to assuming if you add `'n'` you want rendering in operator pending mode.

If you simply want rendering in all modes you can set `render_modes` to `true`:

```lua
require('render-markdown').setup({
  render_modes = true,
})
```

If you want rendering in visual line mode and visual block mode then you'll need to use the actual values for those modes `vl` and `vb` don't mean anything though I get the intuition, checkout `:help mode()`. In your case you'll want to do:

```lua
require('render-markdown').setup({
  render_modes = { ...,  'v', 'V', '\22' },
})
```

The block one is kind of special and needs to be represented as `'\22'` in lua since `CTRL-V` isn't really possible.
