### ISSUE TITLE
bug: checkbox is not rendered correctly 

### ISSUE THREAD

**Issue by Ghasak** [MeanderingProgrammer/render-markdown.nvim#192]
### Neovim version (nvim -v)

0.10.1

### Neovim distribution

N/A

### Operating system

MacOS

### Terminal emulator / GUI

iTerm2.0 Build 3.5.5

### Describe the bug

The `checkbox` is not rendered correctly, I have checked and I found the error comes today, 
I checked to `91ce0b5` and everything works perfectly, see the attached image. 
I  am very much thankful to the developers for all their amazing effort, but I wish to handle some tests before pushing to the main branch. 
![image](https://github.com/user-attachments/assets/8f585efc-7fe3-490c-921a-b8036bc826d2)
![image](https://github.com/user-attachments/assets/11c0915a-b61c-4cf5-b06d-c15508f135f3)

### Expected behavior

Should be rendered as shown in the image below 
![image](https://github.com/user-attachments/assets/cf0eb017-d51e-4376-8a7b-fe10996daa56)

### Healthcheck output

dap: require("dap.health").check()

dap: Adapters ~

dap.adapter: debugpy ~
- Adapter is a function. Can't validate it

dap.adapter: codelldb ~
- OK is executable: /Users/gmbp/.local/share/nvim/mason/packages/codelldb/extension/adapter/codelldb

dap.adapter: python ~
- Adapter is a function. Can't validate it

dap.adapter: rt_lldb ~
- OK is executable: /Users/gmbp/.local/share/nvim/mason/packages/codelldb/extension/adapter/codelldb

dap: Sessions ~
- OK No active sessions

==============================================================================
fzf_lua: health#fzf_lua#check

fzf-lua [required] ~
- OK 'fzf' `0.55.0 (brew)`
- OK 'git' `git version 2.46.0`
- OK 'rg' `ripgrep 14.1.0`
- OK 'fd' `fd 10.2.0`

fzf-lua [optional] ~
- OK `nvim-web-devicons` found
- OK 'rg' `ripgrep 14.1.0`
- OK 'fd' `fd 10.2.0`
- OK 'bat' `bat 0.24.0`
- OK 'delta' `delta 0.18.1`

fzf-lua [optional:media] ~
- OK 'viu' `viu 1.5.0`
- WARNING 'chafa' not found
- WARNING 'ueberzugpp' not found

fzf-lua [env] ~
- OK `FZF_DEFAULT_OPTS` is not set
- OK `FZF_DEFAULT_OPTS_FILE` is not set

### Plugin configuration

```lua 
  {
    "MeanderingProgrammer/markdown.nvim",
    event = "InsertEnter",
    ft = { "markdown" },
    cmd = { "RenderMarkdown" },
    main = "render-markdown",
    opts = {},
    name = "render-markdown", -- Only needed if you have another plugin named markdown.nvim
    --dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.nvim" }, -- if you use the mini.nvim suite
    -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.icons' }, -- if you use standalone mini plugins
    dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" },

    config = function()
      require("plugins.configs.myMarkdown").config()
    end,
  },

```

### Plugin error log

None

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided text for all screenshots & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
Your config here: https://github.com/Ghasak/nvim/blob/main/lua/plugins/configs/myMarkdown.lua, should really not specify all the default values.

You can put those as a comment somewhere for your own reference if that's the goal, but in general if you're using the defaults then provide nothing to the call to setup. You'll avoid needing to migrate during any potential breaking changes as well.

The specific problem here is with setting the `markdown_query` field, which is modified anytime I need to fetch new elements from tree-sitter or sometimes to support a refactor. In this case this commit: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/d3a565eb4c46005a390d4b19f80f9ad719607df6, modified how I handle checkboxes.

The fix would be to remove all of the `_query` fields. I did decide that having these configurations available to users was a bad idea, so they have been removed here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/b0fe71f112d06ae30f49fcd2a35c05e303389f18.

So you can also pull the latest changes and that will also work since that will effectively ignore your queries.

**Comment by Ghasak** [comment]
Thank you very much, very much helpful
