### ISSUE TITLE
help: Make signs not disappear when entering insert mode?

### ISSUE THREAD

**Issue by unphased** [MeanderingProgrammer/render-markdown.nvim#195]
### Neovim version (nvim -v)

NVIM v0.11.0-dev-836+g64847fbdc-Homebrew Build type: Release LuaJIT 2.1.1725453128

### Neovim distribution

custom lazy

### Description

Hi, love the plugin. I like the signs feature. However, they cause a lot of jarring movement when they are removed when entering insert mode, and again when exiting insert mode. 

Is there a way to let them stay put when we enter insert mode? 

If not, sadly I may need to disable signs.

**Comment by MeanderingProgrammer** [comment]
You can enable rendering in all modes by setting `render_modes = true`. This will keep signs along with all other marks around in all modes except for marks on the current cursor row.

Otherwise there is currently no way to keep around only the sign marks when not rendering.

This plugin assumes when rendering is not happening it can avoid listening to updates. Though maybe there is something to be said for a feature to specify which components to render in which modes rather than an all or nothing.

**Comment by unphased** [comment]
Makes a huge amount of sense. The problem about signs is that only in the event that they are removed _and are the only signs set_, then this causes the entire buffer **including the insert mode cursor line** to shift 2 col to the left. 

I'll just disable signs as a way to opt out of it.
