### ISSUE TITLE
feature: "Run" plugin in docstrings

### ISSUE THREAD

**Issue by zippeurfou** [MeanderingProgrammer/render-markdown.nvim#198]
### Is your feature request related to a problem? Please describe.

I am often having to read latex and from time to time markdown "like" formatting in docstring.
Here is a few examples:
[[1](https://github.com/keras-team/keras/blob/v3.5.0/keras/src/layers/activations/prelu.py#L10)] Use code block
[[2](https://github.com/tensorflow/ranking/blob/v0.5.3/tensorflow_ranking/python/keras/losses.py#L755-L829)] Use Latex

### Describe the solution you'd like

I would like to be able to render the docstring with the plugin while editing file.
This might not be perfect as it is not exactly markdown but it would be better than currently where it is just string.

Right now it does work when I specifically call the signature (which is awesome and should be mentioned in readme!).
However, when editing code it does not.
See the screenshot.
1. Calling the signature.

<img width="665" alt="Screenshot 2024-10-04 at 1 07 33 PM" src="https://github.com/user-attachments/assets/7d352efc-03ad-43f6-8807-1a4ba08af8ea">

2. Editing the code

<img width="615" alt="Screenshot 2024-10-04 at 1 07 57 PM" src="https://github.com/user-attachments/assets/f0183120-a912-4071-8677-384adbb9d3b5">

### Describe alternatives you've considered

I am not aware of any alternative.

### Additional information

This by itself could be a different plugin if we wanted to make it "perfect". So I am more thinking about something better than nothing than something perfect. Down the line maybe it is more around Sphinx than markdown but there are lot of common things there.

**Comment by MeanderingProgrammer** [comment]
Hi, glad you like the LSP rendering. It's kind of mentioned in the README, but more vaguely in that it handles all file types so long as they contain `markdown`.

Unfortunately as far as rendering `docstring`s live its not really possible and the issue comes down to leading spaces.

So for instance you can add an injection for python files by creating a file at `~/.config/nvim/after/queries/python/injections.scm` with the following content:

```
;extends

((string_content) @injection.content
  (#set! injection.language "markdown"))
```

This attempts to treat strings, which is what multi-line python comments are, as markdown.

Then adding `python` to the `file_types` list. I could even include doing all this as part of the plugin so you wouldn't need to create the injection.

However it falls apart when we try to render the string since leading spaces are not stripped. They get picked up by treesitter so the entire contents end up being interpreted as an `indented_code_block`. So effectively no styling gets applied.

While it seems like we should be able to ignore leading spaces there's not really any way to do this that I am aware of. Other than writing my own parser, treating the contents as a string and applying offsets when rendering, which is not something I want to touch. There's just a lot of places where the offsets would need to be applied like in concealed content and it would permeate the entire codebase.

**Comment by zippeurfou** [comment]
Thank you @MeanderingProgrammer for your quick reply. 
It all makes sense. 
Very naively, since the lsp signature is able to do it ok as shown in the screenshot and that I only care about it for things that can have signature, couldn't we do something that replace the comment in normal mode with the signature content (eg. Manually calling the signature and replacing it) and in insert show the comment as string like you're doing on the plugin?

**Comment by MeanderingProgrammer** [comment]
When we get the signature from the LSP it's being rendered in it's own buffer with whatever the LSP sends back, which I assumed is the docstring minus leading spaces.

We can't do any kind of buffer in buffer kind of thing in neovim so instead we would need to actually replace text in the buffer.

This opens up a lot of complex problems that are currently avoided because text is never modified, instead extmarks are added and are entirely virtual leaving the text untouched.

You can imagine I would need to replace text in insert mode then a user runs ':w', and then what happens. Well command mode is rendered so the user would end up writing the modified docstrings which they probably don't want. So I would need to listen to something like BufWritePre, switch the text back to it's original state so it's written correctly then after modify it again. 

It would function like a 2 state formatter essentially and that sounds complicated and error prone.

You're welcome to take a stab at implementing this and I'm more than happy to look over it. I tried the approach of modifying the text sent to the parser and applying the offsets to the output a little while back but it ended up too buggy for me to release.

**Comment by agrin96** [comment]
@MeanderingProgrammer sorry to bring this issue back up, but I've also been keen on solving this issue. I tried to implement exactly what you said with modifying the text inline via a custom handler. Bear in mind this is not production quality, just trying to get it to work, but I'm stuck at the point where I have a parsed markdown tree, but I'm not sure how to apply your render markings to the tree to then substitute. 

Is this similar to what you were doing ? 

```lau
        local function parse_python(root, buf)
            local marks = {}
            for id, node in query:iter_captures(root, buf) do
                local capture = query.captures[id]
                local start_row, start_col, end_row, _ = node:range()
                if capture == 'docstring' then
                    local text = vim.api.nvim_buf_get_lines(buf, start_row, end_row, false)
                    local indent = string.find(text[2],"^%s*") + 1
                    for i, _ in ipairs(text) do
                        if i == 1 then
                            goto continue
                        else
                            text[i] = text[i]:sub(indent, -1)
                        end
                        ::continue::
                    end
                    
                    local tempbuf = vim.api.nvim_create_buf(false, true)
                    vim.api.nvim_buf_set_lines(tempbuf, 1, -1, false, text)

                    local parser = vim.treesitter.get_parser(tempbuf, "markdown")
                    local trees = parser:parse(true)
                    print("Length - " .. #trees)
                    -- For each node in the parsed tree its position will simply be the 
                    -- start_row + row, start_col + offset + col
                    -- except the first row which would have a row = 1 and can simply be
                    -- start_row + row, start_col + col
                    table.insert(marks, {
                        conceal = true,
                        start_row = start_row,
                        start_col = 0,
                        opts = {
                            end_row = end_row,
                            end_col = 0,
                        },
                    })
                end
            end
```

**Comment by MeanderingProgrammer** [comment]
I think I can help you get something kind of working, at least in a "good enough" sense but whatever I suggest here is by no means guaranteed to keep working since it'll rely on calling internal functions which are likely to change.

Handlers are all meant to be independent and what you're looking to do here is modify the output of one. They're also not really meant to run across separate buffers and somehow be joined together.

All that is to say this is hacky and could cause something weird to happen or not even work.

Once you have tempbuf I would start the `markdown` parser then call `parse_buffer` method in the `ui` module. You'll need to provide a valid window for the buffer since internally we use information from the window to figure out things like what's actually visible in the view port and how wide is the window.

I don't know how to avoid this logic so you might need to open  `tempbuf` in a window to make this work. So you'll end up with:

```lua
local function parse_python(root, buf)
  ...
  local tempbuf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_lines(tempbuf, 1, -1, false, text)
  vim.treesitter.start(tempbuf, 'markdown')
  local tempwin = -- Some logic to open tempbuf in a window
  local marks = require('render-markdown.core.ui').parse_buffer(tempbuf, tempwin, vim.fn.mode(true))
  -- Modify the output marks to account for offsets
  ...
end
```

**Comment by agrin96** [comment]
Thanks for the response. Looks like its more trouble than its worth. Too bad. Maybe one day.

**Comment by gracepetryk** [comment]
For anyone who comes across this I've [forked](https://github.com/gracepetryk/tree-sitter-markdown/tree/no-indented-blocks) the markdown parser to remove indented code blocks.

You can use the forked parser with `nvim-treesitter` by setting up a `TSUpdate` auto command:
```lua
vim.api.nvim_create_autocmd('User', { pattern = 'TSUpdate',
  callback = function()
    local parser_config = require "nvim-treesitter.parsers"
    parser_config.markdown = {
        install_info = {
          url = 'https://github.com/gracepetryk/tree-sitter-markdown',
          branch='no-indented-blocks',
          -- optional entries
          location = 'tree-sitter-markdown',
          generate = false,
          generate_from_json = false,
        },}
  end
})
```

The only other thing needed to is to copy the markdown queries into neovim's runtime path and remove all the references to `indented_code_block`. This is how I've got it set up in my dotfiles: https://github.com/gracepetryk/dotfiles/tree/5b3bdab84c8cd6bcf1fcf57c86f2cf6f2c240224/nvim/.config/nvim/queries/markdown

<img width="323" height="228" alt="Image" src="https://github.com/user-attachments/assets/3d4878b7-a0ef-4211-8a97-f506cb5606f2" />
