### ISSUE TITLE
help: Markdown’s not rendering as expected

### ISSUE THREAD

**Issue by phuongpd2k** [MeanderingProgrammer/render-markdown.nvim#215]
### Neovim version (nvim -v)

0.10.1

### Neovim distribution

LazyVim

### Description

It seems like my render isn’t loading as expected. Every heading from level 3 has the same background color, and heading 2 doesn’t have a background color at all. Can someone help me resolve this? :(

<img width="835" alt="image" src="https://github.com/user-attachments/assets/646835e7-0609-478f-b840-d2510c75415a">

```lua
  {
    'MeanderingProgrammer/render-markdown.nvim',
    dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.nvim' }, -- if you use the mini.nvim suite
    -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.icons' }, -- if you use standalone mini plugins
    -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' }, -- if you prefer nvim-web-devicons
    ---@module 'render-markdown'
    ---@type render.md.UserConfig
    opts = {
    },
    config = function()
      require('render-markdown').setup({
        latex = {
          enabled = false,
        },
        file_types = { 'markdown' },
        heading = {
          -- border = true,
          -- Alway use virtual lines for heading borders instead of attempting to use empty lines
          border_virtual = true,
          -- Highlight the start of the border using the foreground highlight
          border_prefix = false,
        },
        pipe_table = {
          min_width = 12,
          -- border = { '╓', '╥', '╖', '╟', '╫', '╢', '╙', '╨', '╜', '║', '─' },
          alignment_indicator = '┅',
        },
        code = {
          sign = false,
          width = "block",
        },
        anti_conceal = {
          ignore = {
            link = true,
            code_language = true,
            callout = true,
            quote = true,
          },
        },
      })
    end,
  },

```

**Comment by phuongpd2k** [comment]
Ah, it was just a problem when I was using the OneDark theme. I fixed it by switching to TokyoNight

**Comment by MeanderingProgrammer** [comment]
Glad you got it working :)

The problem comes from the default highlight groups for the heading backgrounds: https://github.com/MeanderingProgrammer/render-markdown.nvim?tab=readme-ov-file#headings

```lua
{
    heading = {
        backgrounds = {
            'RenderMarkdownH1Bg',
            'RenderMarkdownH2Bg',
            'RenderMarkdownH3Bg',
            'RenderMarkdownH4Bg',
            'RenderMarkdownH5Bg',
            'RenderMarkdownH6Bg',
        },
    },
}
```

If your colorscheme implements them (like tokyonight and a few others) it will use the values the author sets.

However if your colorscheme does not then they will link to default highlight groups: https://github.com/MeanderingProgrammer/render-markdown.nvim?tab=readme-ov-file#colors

| Highlight | Default Link |
| --- | --- |
| RenderMarkdownH1Bg | DiffAdd |
| RenderMarkdownH2Bg | DiffChange |
| RenderMarkdownH3Bg | DiffDelete |
| RenderMarkdownH4Bg | DiffDelete |
| RenderMarkdownH5Bg | DiffDelete |
| RenderMarkdownH6Bg | DiffDelete |

As you can see the H3 -> H6 use the same value `DiffDelete`. Your colorscheme most likely sets values for these defaults and whatever value it sets is what you will see.

If you want to stay with `OneDark` rather than using `tokyonight` just to make this plugin look nice you have a few options:

1. Provide other highlights from your colorscheme of choice to the `heading.backgrounds` configuration
2. Use `vim.api.nvim_set_hl` to set reasonable values for `RenderMarkdownH1Bg` .. `RenderMarkdownH6Bg`
3. Create a PR to add highlights for this plugin into `OneDark` directly similar to: https://github.com/navarasu/onedark.nvim/pull/222/files

**Comment by phuongpd2k** [comment]
Yes, thank you! I’ve changed the OneDark theme highlights to custom heading colors for this. ^^
<img width="3008" alt="image" src="https://github.com/user-attachments/assets/c522827f-c90d-4b0d-a556-672256791350">
