### ISSUE TITLE
help: How to customise quote and callouts highlight of the quote body text (not the icon) 

### ISSUE THREAD

**Issue by morgaan** [MeanderingProgrammer/render-markdown.nvim#216]
### Neovim version (nvim -v)

0.11.0-dev

### Neovim distribution

Vanilla Neovim

### Description

If I try the below configuration:

```lua
quote = {
	enable = true,
	highlight = '@text'
},
```

I can see that the highlight applies only to the left border of the quote but not to the body text of the quote that remains just the same as the default `RenderMarkownQuote`.

The issue is that since it links to `@markup.quote` which happens to be bold in my case.  
So if I want to bold some text from the quote it would not show differently than the rest of the body text of the quote defeating the bolding intention.

Is it a bug or a feature to decouple that the `highlight` applies to only to the border?
If the ladder, it would be nice to have the ability to customise the `highlight` for the body text as well in the `quote` config. Same may apply to the Callouts I believe.

**Comment by morgaan** [comment]
I managed to work around this by amending my colorscheme (i.e catpuccin) plugin config:

```lua
return {
	'catppuccin/nvim',
	name = 'catppuccin',
	priority = 1000,
	config = function()
		-- colorscheme catppuccin " catppuccin-latte, catppuccin-frappe, catppuccin-macchiato, catppuccin-mocha
		vim.cmd([[colorscheme catppuccin-frappe]])

		-- Overrides and add-ons
		vim.cmd([[highlight @markup.quote cterm=NONE gui=NONE guifg=#ea999c]])
		vim.cmd([[highlight @text.emphasis cterm=italic gui=italic guifg=#a6d189]])
		vim.cmd([[highlight RenderMarkdownHighlight guifg=#303446 guibg=#f2d5cf]])
	end
}
```

**Comment by MeanderingProgrammer** [comment]
Applying a highlight to only the quote icon is the intended behavior.

The mental model is that  the body of a block quote uses the default highlight group `@markup.quote`, this just comes from nvim-treesitter: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/markdown/highlights.scm#L105-L106.

Since colorschemes should provide values for default groups there's no need to override any of this behavior with this plugin. If you don't like that catpuccin makes block quote bodies bold by default that would be something you resolve with the colorscheme: https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/groups/integrations/treesitter.lua#L112.

So treat the icon in a special way since that is added by this plugin. Let nvim-treesitter and the users colorscheme naturally handle the quote body.
