### ISSUE TITLE
help: heading line highlighting with specific heading color.

### ISSUE THREAD

**Issue by ml3m** [MeanderingProgrammer/render-markdown.nvim#222]
### Neovim version (nvim -v)

0.10.2

### Neovim distribution

N/A

### Description

I've set the Rose Pine Moon theme on both **Kitty** and **Alacritty**, and while it works perfectly on Kitty, **I'm having trouble with it on Alacritty**. I’ve tried various themes and even manually adjusting the colors, but nothing seems to fix the issue. Do you have any ideas why this might be happening? Is Alacritty missing some functionality?

Here’s a screenshot of the Alacritty highlighting:
![image](https://github.com/user-attachments/assets/0219ac43-36ac-4bd3-a34e-2427914ae05b)

**Comment by ml3m** [comment]
It turns out that the theme works in Alacritty *without* Tmux, but when I open a `.md` file within Tmux, it stops working. Interestingly, in Kitty, Tmux doesn’t interfere at all—the theme displays perfectly, whether Tmux is running or not. Any idea why Tmux might be causing this inconsistency in Alacritty? 

Maybe my questions aren’t entirely appropriate for this space, but if anyone knows why this is happening, I’d really appreciate the help!

**Comment by MeanderingProgrammer** [comment]
Unfortunately issues like this are hard to help debug, since it relies on me being able to replicate your setup and is just not related to this plugin, at least directly.

I personally am not sure why tmux would cause an issue in `Alacritty` but not `Kitty`, would definitely expect an all or nothing kind of problem, but maybe `Kitty` does something special to handle tmux sessions? 

I do use tmux and would suggest trying to add the following 2 lines to your config and giving this a shot just as a starting point for the potential issue.

```
set -g default-terminal "tmux-256color"
set -sa terminal-features ",*:RGB"
```

I don't know if these settings are recommended or if they will cause other problems for you but if they fix the issue you should be able to find the root cause faster. The default-terminal setting is most likely the problem but I do know there are problems with setting it like I am.
