### ISSUE TITLE
help: Icons for headings and callouts are extremely small

### ISSUE THREAD

**Issue by sebiwi** [MeanderingProgrammer/render-markdown.nvim#223]
### Neovim version (nvim -v)

0.10.2

### Neovim distribution

LazyVim

### Description

I installed this plugins using the default configuration, and the size of the icons for headings are callouts is so small it's hard to see. I'm using WezTerm, and `MesloLGS Nerd Font Mono`.

See the screenshot below:

<img width="298" alt="Screenshot 2024-11-02 at 12 37 02" src="https://github.com/user-attachments/assets/ff8f001b-66b3-4213-8546-aed0ec62d328">

Is this normal? Is there a way to increase the size of it so it looks like the one in the README examples?

Thanks!

**Comment by sebiwi** [comment]
I just tried this with `JetBrainsMono Nerd Font` and it worked like a charm.

Layer 8 error, sorry for the noise.

**Comment by MeanderingProgrammer** [comment]
Glad you got it working. This typically comes down to the font itself + terminal emulator font rendering logic. Some can fill extra space with larger symbols some can't, is a very case by case thing.

**Comment by sebiwi** [comment]
@MeanderingProgrammer I think a callout to the information on your response on the readme would be helpful, as well as the terminal + font you’re using in your screenshots and demo for clarity.

**Comment by MeanderingProgrammer** [comment]
In your particular case I believe the issue was that you were using a patched mono nerd font `MesloLGS Nerd Font Mono`.

Wezterm has this notion of [font fallbacks](https://wezfurlong.org/wezterm/config/fonts.html#font-related-configuration), so if a symbol is not defined in your main font it will start searching through other fonts to see if they have the symbol. It also comes bundled with nerd font symbols which can expand. So if you were using any non nerd font like `Times New Roman`, you would not have had this problem. For you I would recommend not using a patched nerd font at all and letting Wezterm's fallbacks handle the symbols, but that is for this specific situation.

Unfortunately adding a recommendation for "a nerd font" wouldn't help in this case and explaining why is again very case by case dependent. Kitty has another mechanism for using different fonts for different symbol ranges. Alacritty has neither fallbacks nor symbol overrides AFAIK. Using the same font in different terminal emulators can yield different results since not all of them support the same features like expanding glyphs to fill space.

Edge cases like this, that are specific to each terminal emulator, are why I think a generic statement isn't particularly helpful and a full explanation would be a full document. I'll see if someone else has taken the time to write this doc, if not maybe I'll give it a shot.

**Comment by sebiwi** [comment]
I was going to say that your comment was already insightful, but the guide you produced makes it crystal clear. Thanks a lot!
