### ISSUE TITLE
help: How to change the color for the rendered Latex lines

### ISSUE THREAD

**Issue by NeveIsa** [MeanderingProgrammer/render-markdown.nvim#229]
### Neovim version (nvim -v)

NVIM v0.10.2 Build type: RelWithDebInfo LuaJIT 2.1.1727870382

### Neovim distribution

LazyVim

### Description

How do I change the color of the maths that is rendered from Latex blocks?

I tried the following but it doesn't work. There is no example how to change color in the readme. 
```lua
require("config.lazy")
require('render-markdown').setup({
    latex = {
        enabled = true,
        converter = 'latex2text',
        highlight = 'RenderMarkdownMath',
        top_pad = 0,
        bottom_pad =0,
    },
    colors = {
    	RenderMarkdownMath = 'red'
    }
})

```
Thank you,
Sampad

**Comment by MeanderingProgrammer** [comment]
I think it would help to first understand how colors in neovim work to understand why this doesn't work and how to fix it.

Most of this is generic and not related to this plugin specifically so hopefully it can help you configure colors for all your other plugins.

## How Colors Work

Colors are defined using `highlight groups`. When defining a highlight group you assign it some name, like `Comment`, along with a value. The value can either be hex colors, like `#ff0000` for red, for the foreground / background, or it can link to another highlight group which means use the same value as this other one.

To see all the highlight groups that exist along with their values you can run the `:highlight` command. To see the value for a specific highlight group, like `RenderMarkdownMath`, you can run `:highlight RenderMarkdownMath`.

Common highlight groups come with some default definitions by neovim out of the box, but these are likely overridden by your colorscheme. All text on the screen is associated with some highlight group which neovim will get the definition for to figure out how to color it.

## Why the Attempt Doesn't Work

When you do:

```lua
require('render-markdown').setup({
    colors = { RenderMarkdownMath = 'red' },
})
```

All you're doing is assigning a value to a key in a Lua table. Naturally putting a key in a table isn't going to do anything on its own to change the definition for a highlight group. Changing the definition requires interacting with neovim, either via a command or through the Lua API.

This would work if the plugin had a `colors` configuration option and used that value to call the API, but if you expand the Default Configuration under [Setup](https://github.com/MeanderingProgrammer/render-markdown.nvim?tab=readme-ov-file#setup) you'll see there's no such option.

## How to Fix

By default the highlight group for latex lines is `RenderMarkdownMath`. This highlight group links to the common highlight group `@markup.math`, see [Color Definitions](https://github.com/MeanderingProgrammer/render-markdown.nvim?tab=readme-ov-file#colors). This common highlight group is likely defined by your colorscheme and that is the color you currently see.

To change the color we either need to change the highlight group being used to some other one, or change the color value for the default highlight group `RenderMarkdownMath`. Either of these will work so pick whichever approach you prefer.

### 1) Change the Highlight Group

First you'll need to find a highlight group with a color that you want to use instead, use the `:highlight` command to help you find one, for me `DiagnosticError` has a reddish value.

Now you just need to update the configuration to change the highlight group being used for latex:

```lua
require('render-markdown').setup({
    latex = { highlight = 'DiagnosticError' },
})
```

Be aware that the value for `DiagnosticError` is likely to change if you change colorschemes. This can be a good thing since it'll likely match the overall aesthetic of the colorscheme or a bad thing if you wanted it to always stay the same, up to you.

### 2) Changing the Color of RenderMarkdownMath

To do this use the `vim.api.nvim_set_hl` API to change the value associated with `RenderMarkdownMath`.

You can take a similar approach as the previous option and link the value to `DiagnosticError`, this is an alternative to setting the highlight configuration but is functionally equivalent:

```lua
vim.api.nvim_set_hl(0, 'RenderMarkdownMath', { link = 'DiagnosticError' })
require('render-markdown').setup({})
```

Or you can use the same API to set a static color value that will not change based on colorscheme:

```lua
vim.api.nvim_set_hl(0, 'RenderMarkdownMath', { fg = '#ff0000' })
require('render-markdown').setup({})
```

You can really play around with the API to make it how you want it, see `:h nvim_set_hl`, for instance to make it red & bold:

```lua
vim.api.nvim_set_hl(0, 'RenderMarkdownMath', { fg = '#ff0000', bold = true })
require('render-markdown').setup({})
```
