### ISSUE TITLE
feature: styling for bare URLs & comments

### ISSUE THREAD

**Issue by chrisgrieser** [MeanderingProgrammer/render-markdown.nvim#244]
### Is your feature request related to a problem? Please describe.

This plugin really has come a long way, congrats for that.

The only two things I noticed that are not handled by the plugin yet are `<!-- toc -->` and [bare URLs](https://github.com/updownpress/markdown-lint/blob/master/rules/034-no-bare-urls.md).

### Describe the solution you'd like

I think in both cases, bare URLs and comments, they could be concealed, with only one icon left to indicate the presence of content maybe?

### Describe alternatives you've considered

I am not aware of any.

**Comment by MeanderingProgrammer** [comment]
For bare URLs are you talking about actual bare URL, like `http://www.example.com/`, or the ones surrounded by angle brackets, like `<http://www.example.com/>`?

I'll add support for the latter, but will probably handle it more like emails where the angle brackets are hidden and an icon is added rather than hiding the whole thing. For the former since these are not handled by the treesitter parser I'm not going to handle them.

I've generally stayed away from touching any HTML entities, but maybe comments are a good exception to this. I'll provide a `custom_handler` version shortly in case I don't end up adding it.

**Comment by chrisgrieser** [comment]
> For bare URLs are you talking about actual bare URL, like http://www.example.com/, or the ones surrounded by angle brackets, like <http://www.example.com/>?

That makes sense, as markdownlint as well as some parsers expect angel brackets, making it somewhat the idiomatic way of writing urls (https://github.com/updownpress/markdown-lint/blob/master/rules/034-no-bare-urls.md)

> I'll add support for the latter, but will probably handle it more like emails where the angle brackets are hidden and an icon is added rather than hiding the whole thing. 

yep, that sounds good!

**Comment by MeanderingProgrammer** [comment]
Bare URL support added here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/401a6c9c4cf39e22b8487503dd7dfe37fc7fb064

**Comment by MeanderingProgrammer** [comment]
Here's what a custom handler for concealing HTML comments would look like:

```lua
---@param root TSNode
---@param buf integer
---@return render.md.Mark[]
local function hide_comments(root, buf)
    local marks = {}
    local query = vim.treesitter.query.parse('html', '(comment) @comment')
    for id, node in query:iter_captures(root, buf) do
        local capture = query.captures[id]
        local start_row, start_col, end_row, end_col = node:range()
        if capture == 'comment' then
            table.insert(marks, {
                conceal = true,
                start_row = start_row,
                start_col = start_col,
                opts = { end_row = end_row, end_col = end_col, conceal = '' },
            })
        end
    end
    return marks
end

require('render-markdown').setup({
    custom_handlers = {
        html = { parse = hide_comments },
    },
})
```

**Comment by chrisgrieser** [comment]
> Here's what a custom handler for concealing HTML comments would look like

Thanks! I prefer having them not completely hidden, but I realized that it's just the `conceal` key. Tbh, I think this should be builtin rather than a custom parser. They may be called "html" comments, but they are in practice also the standard comment syntax for Markdown. Many tools (linters, formatters, LSPs) use this comment syntax for their ignore comments. 

> Bare URL support added here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/401a6c9c4cf39e22b8487503dd7dfe37fc7fb064

Thanks, looks like a charm!

There appears to a visual glitch when passing such bare URLs though, which does not happens with other conceals by this plugin:

https://github.com/user-attachments/assets/702b8acc-fe29-4089-9182-e7d4c4a45798

**Comment by MeanderingProgrammer** [comment]
That definitely doesn't look good. Out of curiosity what terminal emulator / GUI are you running neovim in?

To remove the angle brackets and add the icon I used a single extmark that hid the entire line then added it back inlined with icon plus the URL minus brackets. Since that's effectively removing and adding back the entire line it ends up having this pretty bad behavior.

Fixed this here hopefully: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/b6b903cc09df1441602fc04665fb12cef576a914.

Separated the logic into 4 smaller marks to hide brackets, add the icon, and highlight the URL.

Can you update and LMK if it's better on your end, I'm not able to replicate that behavior on my end.

**Comment by MeanderingProgrammer** [comment]
Added support for concealing HTML comments here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/558310ae07b7bf0dffc478160513bb5c845f263c

**Comment by MeanderingProgrammer** [comment]
Sure added support for this here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/7674543331701d05dc9f878e1fe62d1107dc2f5e

By default no value is set so it will still just conceal the comment out of the box. You just need to provide a value for `html.comment.text`:

```lua
require('render-markdown').setup({
    html = { comment = { text = 'SOME VALUE' } },
})
```

I used inline text rather than a conceal character so you're free to use a value as long or short as you want.

**Comment by chrisgrieser** [comment]
Perfect, thank you!

**Comment by chrisgrieser** [comment]
Just send you a small coffee (or two, depending on where you live) for all your awesome work and quick responses. Cheers!

**Comment by polirritmico** [comment]
Hi, shouldn't be this opt-in instead of opt-out? IMO concealing content is really a personal preference.

**Comment by MeanderingProgrammer** [comment]
I see it in the same way as concealing links and other content that's concealed out of the box. HTML comments are the same level of information as a link URL. If concealing content is intrusive you can opt out of it via:

```lua
opts = {
    win_options = { conceallevel = { rendered = 0 } },
}
```

In which case the HTML comment concealing would also be disabled. Otherwise it's a case by case thing that is left up to you to decide. In general all new features that aren't new options for an existing feature will be enabled by default with some way to opt out.
